---
- name: Ensure Riemann download directory exists
  file:
    path: "{{ riemann_download_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- include: install_from_tarball.yml
  when: riemann_use_tarball

- include: install_from_package.yml
  when: riemann_use_package
